### ISSUE TITLE
general practitioner research topic: simband in daily patient care

### ISSUE THREAD

**Issue by kevinleog** [votb/voiceofthebody.io#3]
I am a general practitioner based in Belgium, I am currently initiating a research topic "simband in daily patient care", trying to find partners with a cloud based solution for patient daily monitoring, based on Simband. please contact me in case you want to join us or discuss the possibilities.

Kevin_l_g@hotmail.com

**Comment by kushalvora** [comment]
Hi Kevin,

Thank you for your interest in Simband. We have started accepting application for Simband: http://www.voiceofthebody.io/simband/development-kits.html

We highly encourage you to contact us using the proper channel, that way your expression of interest is not lost.

Kushal
